# Data Cleaning: building permits issued in San Francisco

In this notebook we'll discover how to clean a dataset using some simple techniques for missing values.

The **San Francisco building permits** dataset can be found in [Kaggle](https://www.kaggle.com/aparnashastry/building-permit-applications-data). For more information about the data, there is a data dictionary included in Kaggle's dataset.

## 1) Have a look at the data

Run the following code to load in the libraries and dataset we'll use:

In [5]:
# modules
import pandas as pd
import numpy as np

In [6]:
# read in all our data
sf_permits = pd.read_csv("Building_Permits.csv")

C:\Users\ideloma\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Print the first five rows of our loaded dataset:

In [7]:
sf_permits.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

As it can be checked from these first rows, there are already some missing values. We'll check them in the following section.

## 2) How many missing data points do we have?

It is a good practice to see what is the percentage of missing values in our dataset:

In [14]:
# total values
total_values = np.product(sf_permits.shape)

# total missing values
missing_values = sf_permits.isnull().sum().sum()

# percent of missing data
percent_missing = (missing_values / total_values) * 100
print(percent_missing)

26.26002315058403

We're missing above 26% of our data! Next, we'll have a closer look at some of the columns with missing values and try to understand what is happening to them.

## 3) Figure out why the data is missing

With missing values the following question needs to be considered:

**Is this value missing because it wasn't recorded or because it doesn't exist?**

For example, in a dataset related to houses there migh be a variable that states if the house have a swimming or not. In that case, missing values could state that there is no swimming pool. On the other hand, a variable such as the house square meters is more probable to be missing because it was not recorded.

Let's have a look to the missing values of our dataset:

In [18]:
# sort the variables by descending order of missing values
sf_permits.isnull().sum().sort_values(ascending=False)

TIDF Compliance                           198898
Voluntary Soft-Story Retrofit             198865
Unit Suffix                               196939
Street Number Suffix                      196684
Site Permit                               193541
Structural Notification                   191978
Fire Only Permit                          180073
Unit                                      169421
Completed Date                            101709
Permit Expiration Date                     51880
Existing Units                             51538
Proposed Units                             50911
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Number of Proposed Stories                 42868
Number of Existing Stories                 42784
Proposed Use                               42439
Existing Use                               41114
Estimated Cost                             38066
Plansets                                   37309
First Construction Document Date           14946
Issued Date                                14940
Revised Cost                                6066
Street Suffix                               2768
Neighborhoods - Analysis Boundaries         1725
Supervisor District                         1717
Zipcode                                     1716
Location                                    1700
Description                                  290
Lot                                            0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Record ID                                      0
Street Number                                  0
Street Name                                    0
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Permit Number                                  0
dtype: int64

In the case of the **"Street Number Suffix"**, it is likely becuase it does not exist. For the **"Zipcode"** conversely, most probably it was not recorded.

## 4) Drop missing values: rows

One of the simplest methods of dealing with missing values is dropping the measurements that contain them. Be careful with this practice, since lots of data can be lost and worse results are obtained later.

Let's see what happens if we drop the rows that contain missing values:

In [28]:
# copy the dataset to avoid changes in the original dataset
sf_permits_copy = sf_permits.copy()

# drop missing values
sf_permits_copy.dropna(axis=0)

Empty DataFrame
Columns: [Permit Number, Permit Type, Permit Type Definition, Permit Creation Date, Block, Lot, Street Number, Street Number Suffix, Street Name, Street Suffix, Unit, Unit Suffix, Description, Current Status, Current Status Date, Filed Date, Issued Date, Completed Date, First Construction Document Date, Structural Notification, Number of Existing Stories, Number of Proposed Stories, Voluntary Soft-Story Retrofit, Fire Only Permit, Permit Expiration Date, Estimated Cost, Revised Cost, Existing Use, Existing Units, Proposed Use, Proposed Units, Plansets, TIDF Compliance, Existing Construction Type, Existing Construction Type Description, Proposed Construction Type, Proposed Construction Type Description, Site Permit, Supervisor District, Neighborhoods - Analysis Boundaries, Zipcode, Location, Record ID]
Index: []

[0 rows x 43 columns]

Wow! There's no dataset if we drop the rows containing missing values.

## 5) Drop missing values: columns

We'll drop the columns that contain missing values to see what happens too:

In [32]:
# copy the dataset to avoid changes in the original dataset
sf_permits_copy2 = sf_permits.copy()

# drop missing values
sf_permits_copy.dropna(axis=1)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,issued,12/05/2017,12/05/2017,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,Bush,issued,12/06/2017,12/05/2017,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,issued,12/06/2017,12/06/2017,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,issued,12/06/2017,12/06/2017,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,issued,12/07/2017,12/07/2017,1489796283803

Originally there where 43 columns, and 12 columns after dropping the columns with missing values. Despite we still have kept all rows, the dataset has shrink significantly.

## 6) Fill in missing values automatically

An easy method to fill in the missing values is replacing them with whatever value that comes after it in the same column. This makes sense for datasets where the observations have some sort of logical order.

We'll perform this method and if there's still any missing value, they'll be replace with zeros:

In [43]:
# copy the dataset to avoid changes in the original dataset
sf_permits_copy3 = sf_permits.copy()

# replace missing values
sf_permits_copy3 = sf_permits_copy3.fillna(method="bfill", axis=0).fillna(0)

# show first five rows
sf_permits_copy3.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,A,Ellis,St,...,3.0,constr type 3,1.0,constr type 1,Y,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,A,Geary,St,...,3.0,constr type 3,1.0,constr type 1,Y,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,A,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,Y,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,A,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),Y,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,A,Market,St,...,3.0,constr type 3,1.0,constr type 1,Y,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

Finally, check that there's no missing value:

In [41]:
a.isnull().sum().sum()

0

We have removed all missing values from the dataset!